import 'package:uuid/uuid.dart';
import '../models/hive_models.dart';
import '../models/activity_item.dart';

const uuid = Uuid();

// ============ Mock Projects ============
final mockProjects = [
  ProjectModel(
    id: uuid.v4(),
    name: 'Riverside Residency',
    location: 'Ahmedabad, Gujarat',
    workerCount: 42,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 90)),
    updatedAt: DateTime.now(),
  ),
  ProjectModel(
    id: uuid.v4(),
    name: 'NH-48 Flyover',
    location: 'Vadodara, Gujarat',
    workerCount: 58,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 120)),
    updatedAt: DateTime.now(),
  ),
  ProjectModel(
    id: uuid.v4(),
    name: 'Greenfield Warehouse',
    location: 'Surat, Gujarat',
    workerCount: 35,
    isActive: false,
    createdAt: DateTime.now().subtract(const Duration(days: 180)),
    updatedAt: DateTime.now().subtract(const Duration(days: 30)),
  ),
];

// ============ Mock Workers ============
final mockWorkers = [
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    role: 'Mason',
    dailyWage: 600.0,
    isHourly: false,
    avatarInitials: 'RK',
    daysWorkedThisMonth: 22,
    totalAdvance: 2000.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 45)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Priya Sharma',
    phone: '+91 87654 32109',
    role: 'Laborer',
    dailyWage: 400.0,
    isHourly: false,
    avatarInitials: 'PS',
    daysWorkedThisMonth: 20,
    totalAdvance: 1500.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 60)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Vikram Singh',
    phone: '+91 76543 21098',
    role: 'Painter',
    dailyWage: 500.0,
    isHourly: false,
    avatarInitials: 'VS',
    daysWorkedThisMonth: 21,
    totalAdvance: 0.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 55)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Anil Patel',
    phone: '+91 65432 10987',
    role: 'Electrician',
    dailyWage: 700.0,
    isHourly: false,
    avatarInitials: 'AP',
    daysWorkedThisMonth: 19,
    totalAdvance: 3000.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 70)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Deepak Gupta',
    phone: '+91 54321 09876',
    role: 'Carpenter',
    dailyWage: 650.0,
    isHourly: false,
    avatarInitials: 'DG',
    daysWorkedThisMonth: 23,
    totalAdvance: 500.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 50)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Mohan Das',
    phone: '+91 43210 98765',
    role: 'Laborer',
    dailyWage: 400.0,
    isHourly: false,
    avatarInitials: 'MD',
    daysWorkedThisMonth: 18,
    totalAdvance: 1000.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 65)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Sangeeta Rao',
    phone: '+91 32109 87654',
    role: 'Plumber',
    dailyWage: 550.0,
    isHourly: false,
    avatarInitials: 'SR',
    daysWorkedThisMonth: 20,
    totalAdvance: 2500.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 75)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Rohan Verma',
    phone: '+91 21098 76543',
    role: 'Mason',
    dailyWage: 600.0,
    isHourly: false,
    avatarInitials: 'RV',
    daysWorkedThisMonth: 21,
    totalAdvance: 0.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 40)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Neha Singh',
    phone: '+91 10987 65432',
    role: 'Laborer',
    dailyWage: 400.0,
    isHourly: false,
    avatarInitials: 'NS',
    daysWorkedThisMonth: 22,
    totalAdvance: 800.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 35)),
    updatedAt: DateTime.now(),
  ),
  WorkerModel(
    id: uuid.v4(),
    projectId: mockProjects[0].id,
    name: 'Suresh Joshi',
    phone: '+91 09876 54321',
    role: 'Painter',
    dailyWage: 500.0,
    isHourly: false,
    avatarInitials: 'SJ',
    daysWorkedThisMonth: 19,
    totalAdvance: 1200.0,
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 80)),
    updatedAt: DateTime.now(),
  ),
];

// ============ Mock Activity Items ============
final mockActivityItems = [
  ActivityItem(
    id: uuid.v4(),
    workerId: mockWorkers[0].id,
    workerName: 'Rajesh Kumar',
    action: 'Marked Present',
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    iconName: 'check_circle',
    color: '#22C55E',
  ),
  ActivityItem(
    id: uuid.v4(),
    workerId: mockWorkers[1].id,
    workerName: 'Priya Sharma',
    action: 'Given ₹1,500 advance',
    timestamp: DateTime.now().subtract(const Duration(hours: 5)),
    iconName: 'currency_rupee',
    color: '#F97316',
  ),
  ActivityItem(
    id: uuid.v4(),
    workerId: mockWorkers[2].id,
    workerName: 'Vikram Singh',
    action: 'Marked Half-Day',
    timestamp: DateTime.now().subtract(const Duration(hours: 8)),
    iconName: 'schedule',
    color: '#EAB308',
  ),
  ActivityItem(
    id: uuid.v4(),
    workerId: mockWorkers[3].id,
    workerName: 'Anil Patel',
    action: 'Added 3 hours OT',
    timestamp: DateTime.now().subtract(const Duration(hours: 12)),
    iconName: 'timer',
    color: '#3B82F6',
  ),
  ActivityItem(
    id: uuid.v4(),
    workerId: mockWorkers[4].id,
    workerName: 'Deepak Gupta',
    action: 'Marked Absent',
    timestamp: DateTime.now().subtract(const Duration(hours: 24)),
    iconName: 'close_circle',
    color: '#EF4444',
  ),
];
